#!/bin/bash

###############################################################################
#    (C) 2012 hyperclock (aka Jimmy M. Coleman)
#	 website:  www.dolphin-os.net
#	 email:    hyperclock(at)dolphin-os(dot)net
#	 git:	   https://github.com/hyperclock/dolphin-build-tool
# 
###############################################################################
###############################################################################
#    dolphin-build-tool - Scripts designed to build DolphinOS based on Ubuntu.
#
#    dolphin-build-tool is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    dolphin-build-tool is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy (see docs/gpl-3.0.txt) of the GNU General 
#    Public License along with dolphin-build-tool.  If not, see 
#    <http://www.gnu.org/licenses/>.
#
################################################################################



. config

IMGDIR=$PWD/images
rm -rf $WORKINGDIR/dolphin-repo-key
mkdir -p $WORKINGDIR/dolphin-repo-key
cd $WORKINGDIR/dolphin-repo-key

mkdir -p dolphin-repo-key/debian
mkdir -p dolphin-repo-key/keyrings
cd dolphin-repo-key
cp $IMGDIR/dolphinos-repo-key.gpg keyrings/dolphinos-repo-key.gpg

EDITOR=true dch --create --package dolphin-repo-key -v $VERSION-$KEYRING_VERSION "Automatically generated"
sed -i "/XXXXXX/d;s/UNRELEASED/$RELEASE/" debian/changelog

cat > debian/control <<EOF
Source: dolphin-repo-key
Section: misc
Priority: optional
Maintainer: Jimmy M Coleman <hyperclock@dolphin-os.net>
Standards-Version: 3.9.3
Homepage: http://www.dolphin-os.net/

Package: dolphin-repo-key
Architecture: all
Depends: gnupg (>= 1.0.6-4), apt
Description: GnuPG key of the DolphinOS repository
 The DolphinOS repository digitally signs its Release files. This package
 contains the repository key used for that.
EOF

cat > debian/postinst <<EOF
#!/bin/sh

if [ -x /usr/bin/apt-key ]; then
    /usr/bin/apt-key add /usr/share/keyrings/dolphinos-repo-key.gpg
fi

EOF
chmod 755 debian/postinst

cat > debian/copyright << EOF
This is DolphinOS's GnuPG keyrings of archive keys.

This package was originally put together by Michael Vogt
<mvo@debian.org> 

The keys in the keyrings don't fall under any copyright.  Everything
else in the package is covered by the GNU GPL.

Debian support files Copyright (C) 2006 Michael Vogt <mvo@debian.org> 
based on the debian-keyring package maintained by James Troup 

Debian support files for debian-archive-keyring are free software; you
can redistribute them and/or modify them under the terms of the GNU
General Public License as published by the Free Software Foundation;
either version 2, or (at your option) any later version.

Debian support files for debian-archive-keyring are distributed in the
hope that they will be useful, but WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License with
your Debian system, in /usr/share/common-licenses/GPL, or with the
Debian GNU debian-archive-keyring source package as the file COPYING.
If not, write to the Free Software Foundation, Inc., 51 Franklin Street,
Fifth Floor, Boston, MA 02110-1301 USA.
EOF

cat > debian/prerm << EOF
#!/bin/sh

case "$1" in
    remove|purge)
	if [ -x /usr/bin/apt-key ]; then
		/usr/bin/apt-key del 12345678
	fi
	;;
esac
EOF
chmod 755 debian/prerm

cat > debian/rules <<EOF
#!/usr/bin/make -f
# debian/rules file - for debian/keyring
# Based on sample debian/rules file - for GNU Hello (1.3).
# Copyright 1994,1995 by Ian Jackson.
# Copyright 1998-2003 James Troup
# Copyright 2011 Stefano Karapetsas
# I hereby give you perpetual unlimited permission to copy,
# modify and relicense this file, provided that you do not remove
# my name from the file itself.  (I assert my moral right of
# paternity under the Copyright, Designs and Patents Act 1988.)
# This file may have to be extensively modified

install_dir=install -d -m 755
install_file=install -m 644
install_script=install -m 755
install_binary=install -m 755 -s

VERSION := $(shell dpkg-parsechangelog | grep ^Version: | cut -d' ' -f2)

build:

clean:
	$(checkdir)
	-rm -f foo foo.asc *.bak *~ */*~ debian/files* debian/*substvars
	-rm -rf debian/tmp

binary-indep: checkroot
	$(checkdir)
	-rm -rf debian/tmp
	$(install_dir) debian/tmp/DEBIAN/
	$(install_script) debian/postinst debian/tmp/DEBIAN/
	$(install_script) debian/prerm debian/tmp/DEBIAN/

	$(install_dir) debian/tmp/usr/share/keyrings/
	$(install_file) keyrings/dolphinos-repo-key.gpg debian/tmp/usr/share/keyrings/

	$(install_dir) debian/tmp/usr/share/doc/dolphinos-repo-keyring/
	$(install_file) debian/changelog debian/tmp/usr/share/doc/dolphinos-repo-keyring/changelog
	$(install_file) debian/copyright debian/tmp/usr/share/doc/dolphinos-repo-keyring/

	dpkg-gencontrol -pdolphinos-repo-key -isp
	chown -R root.root debian/tmp
	chmod -R go=rX debian/tmp
	dpkg --build debian/tmp ..

binary-arch: all

define checkdir
	test -f keyrings/dolphinos-repo-key.gpg
endef

# Below here is fairly generic really

binary:		binary-indep binary-arch

checkroot:
	$(checkdir)
	test root = "`whoami`"

.PHONY: binary binary-arch binary-indep clean checkroot

EOF
chmod 755 debian/rules


dpkg-buildpackage $DPKGOPTS
cd ..
reprepro -Vb $REPODST include $RELEASE dolphin-repo-key*.changes

